# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

local_repository(
    name = "rules_cros",
    path = "../../../src/platform/rules_cros",
)

load("@rules_cros//cros:repositories.bzl", "rules_cros_dependencies")

rules_cros_dependencies()

load("//cargo:crates.bzl", "raze_fetch_remote_crates")

raze_fetch_remote_crates()
